mqtt:
  broker: "[CHANGEME]"
  port: 1883
  username: "[CHANGEME]"
  password: "[CHANGEME]"
  base_topic: "home/ups"
  client_id: "nut-upsc-bridge"

ups:
  name: "[CHANGEME]"
  friendly_name: "[CHANGEME]"
  sw_version: "nut-upsc-bridge-1"
  poll_interval: 30 # seconds

sensors:
  - key: "battery.charge"
    unit: "%"
    type: "sensor"
    icon: "mdi:battery"
    friendly_name: "Battery Charge"
    device_class: "battery"

  - key: "battery.charge.low"
    unit: "%"
    type: "sensor"
    icon: "mdi:battery-10"
    friendly_name: "Battery Low Setpoint"

  - key: "battery.charge.warning"
    unit: "%"
    type: "sensor"
    icon: "mdi:battery-10"
    friendly_name: "Battery Warning Setpoint"
    device_class: "battery"

  - key: "battery.runtime"
    unit: "s"
    type: "sensor"
    icon: "mdi:timer-sand"
    friendly_name: "Battery Runtime"
    device_class: "duration"

  - key: "battery.runtime.low"
    unit: "s"
    type: "sensor"
    icon: "mdi:timer-sand-empty"
    friendly_name: "Low Battery Runtime"
    device_class: "duration"

  - key: "battery.voltage"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash"
    friendly_name: "Battery Voltage"
    device_class: "voltage"

  - key: "battery.voltage.nominal"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash-outline"
    friendly_name: "Nominal Battery Voltage"
    device_class: "voltage"

  - key: "battery.type"
    type: "sensor"
    icon: "mdi:information"
    friendly_name: "Battery Chemistry"

  - key: "input.transfer.high"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash-alert"
    friendly_name: "High Voltage Transfer"
    device_class: "voltage"

  - key: "input.transfer.low"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash"
    friendly_name: "Low Voltage Transfer"
    device_class: "voltage"

  - key: "input.voltage"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash"
    friendly_name: "Input Voltage"
    device_class: "voltage"

  - key: "input.voltage.nominal"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash-outline"
    friendly_name: "Nominal Input Voltage"
    device_class: "voltage"

  - key: "output.voltage"
    unit: "V"
    type: "sensor"
    icon: "mdi:flash"
    friendly_name: "Output Voltage"
    device_class: "voltage"

  - key: "ups.load"
    unit: "%"
    type: "sensor"
    icon: "mdi:gauge"
    friendly_name: "Load"

  - key: "ups.realpower.nominal"
    unit: "W"
    type: "sensor"
    icon: "mdi:flash"
    friendly_name: "Nominal Real Power"
    device_class: "power"

  - key: "ups.beeper.status"
    type: "sensor"
    icon: "mdi:volume-high"
    friendly_name: "Beeper Status"

  - key: "ups.status"
    type: "sensor"
    icon: "mdi:power"
    friendly_name: "Status Data"

  - key: "ups.delay.shutdown"
    unit: "s"
    type: "sensor"
    icon: "mdi:timer-sand"
    friendly_name: "Load Shutdown Delay"
    device_class: "duration"

  - key: "ups.delay.start"
    unit: "s"
    type: "sensor"
    icon: "mdi:timer-sand"
    friendly_name: "Load Restart Delay"
    device_class: "duration"

  - key: "ups.timer.shutdown"
    unit: "s"
    type: "sensor"
    icon: "mdi:timer-stop-outline"
    friendly_name: "Load Shutdown Timer"
    device_class: "duration"

  - key: "ups.timer.start"
    unit: "s"
    type: "sensor"
    icon: "mdi:timer-play-outline"
    friendly_name: "Load Start Timer"
    device_class: "duration"
